const std = @import("std");
const cfgmod = @import("config.zig");
const configfile = @import("configfile.zig");
const jsonmod = @import("json.zig");
const term = @import("term.zig");

/// One environment API key detected on this machine: the provider whose
/// env_keys matched and the name of the variable that was set.
pub const DetectedKey = struct {
    provider: []const u8,
    env_key: []const u8,
};

/// Result of scanning the environment for API keys.
pub const Detection = struct {
    /// Providers with a set env key, in provider-table order (first matching
    /// env var per provider).
    keys: []DetectedKey,
    /// Whether the TAU_API_KEY fallback is set.
    tau_fallback: bool,
};

/// Scan every provider's env_keys for a set (non-empty) environment variable.
/// Also reports TAU_API_KEY, the provider-agnostic fallback.
pub fn detectKeys(arena: std.mem.Allocator, env: *std.process.Environ.Map) !Detection {
    var keys: std.ArrayList(DetectedKey) = .empty;
    for (cfgmod.providers) |p| {
        for (p.env_keys) |ek| {
            if (env.get(ek)) |v| {
                if (v.len > 0) {
                    try keys.append(arena, .{ .provider = p.name, .env_key = ek });
                    break;
                }
            }
        }
    }
    const tau = env.get("TAU_API_KEY") orelse "";
    return .{ .keys = try keys.toOwnedSlice(arena), .tau_fallback = tau.len > 0 };
}

/// Choose the provider for the scaffolded config: an explicit --provider wins,
/// else the first provider with a detected env key, else the default provider.
pub fn pickProvider(det: Detection, provider_opt: ?[]const u8) cfgmod.Provider {
    if (provider_opt) |n| {
        if (cfgmod.findProvider(n)) |p| return p.*;
    }
    if (det.keys.len > 0) {
        if (cfgmod.findProvider(det.keys[0].provider)) |p| return p.*;
    }
    return cfgmod.providers[0];
}

/// Render the commented starter config (JSONC: // and /* */ comments are
/// stripped by configfile.load). Never embeds secret values — detected keys
/// are referenced by env var name only.
pub fn renderConfig(arena: std.mem.Allocator, det: Detection, p: cfgmod.Provider) ![]u8 {
    var buf: std.ArrayList(u8) = .empty;

    try buf.appendSlice(arena,
        \\// tau configuration -- generated by `tau init`.
        \\// This file is JSONC: "//" line comments and "/* block */" comments are ignored.
        \\// Reference: docs/configuration.md | `tau guide` | `tau --help`
        \\//
        \\// API key resolution order:
        \\//   --api-key flag > keys["<provider>"] > provider env var > "api_key" > TAU_API_KEY
        \\//
        \\// Provider API-key environment variables (* = detected on this machine):
        \\
    );
    for (cfgmod.providers) |pv| {
        try buf.appendSlice(arena, "//   ");
        if (pv.env_keys.len == 0) {
            try buf.appendSlice(arena, "(none)");
        } else {
            for (pv.env_keys, 0..) |ek, i| {
                if (i != 0) try buf.appendSlice(arena, " | ");
                try buf.appendSlice(arena, ek);
            }
        }
        try buf.appendSlice(arena, "  -> \"");
        try buf.appendSlice(arena, pv.name);
        try buf.append(arena, '"');
        for (det.keys) |k| {
            if (std.mem.eql(u8, k.provider, pv.name)) {
                try buf.appendSlice(arena, "  * ");
                try buf.appendSlice(arena, k.env_key);
                try buf.appendSlice(arena, " is set");
            }
        }
        try buf.append(arena, '\n');
    }
    try buf.appendSlice(arena, "//   TAU_API_KEY  -> fallback for any provider");
    if (det.tau_fallback) try buf.appendSlice(arena, "  * set");
    try buf.append(arena, '\n');
    if (det.keys.len == 0 and !det.tau_fallback) {
        try buf.appendSlice(arena, "//   none detected -- export one of the env vars above, or set \"api_key\" below\n");
    }
    try buf.appendSlice(arena, "//\n{\n");

    try buf.appendSlice(arena,
        \\  // Active provider. One of:
        \\
    );
    try buf.appendSlice(arena, "  //   ");
    for (cfgmod.providers, 0..) |pv, i| {
        if (i != 0) try buf.appendSlice(arena, " | ");
        try buf.appendSlice(arena, pv.name);
    }
    try buf.appendSlice(arena,
        \\
        \\  // The API endpoint is derived from the provider; the TAU_ENDPOINT env
        \\  // var overrides it. "model" defaults to the provider's default model.
        \\  "provider": "
    );
    try buf.appendSlice(arena, p.name);
    try buf.appendSlice(arena, "\",\n\n");

    try buf.appendSlice(arena, "  // \"model\": \"");
    try buf.appendSlice(arena, p.default_model);
    try buf.appendSlice(arena,
        \\",
        \\
        \\  // Global API key, used when no keys[] entry or env var matches.
        \\  // Prefer env vars -- this file is plaintext. Uncomment to set:
        \\  // "api_key": "sk-...",
        \\
        \\  // Per-provider API keys (an entry outranks that provider's env var):
        \\  // "keys": { "openai": "sk-..." },
        \\
        \\  // Output mode: "json" (agent-friendly) or "text" (human-readable).
        \\  "mode": "json",
        \\
        \\  // Stream responses token-by-token.
        \\  "stream": true,
        \\
        \\  // Sampling temperature.
        \\  "temperature": 0.7,
        \\
        \\  // Auto-compaction: summarize history when estimated tokens exceed
        \\  // compact_threshold of the model's context window.
        \\  "auto_compact": true,
        \\  "compact_threshold": 0.5
        \\}
        \\
    );
    return buf.toOwnedSlice(arena);
}

fn appendJsonStr(arena: std.mem.Allocator, buf: *std.ArrayList(u8), s: []const u8) !void {
    try buf.append(arena, '"');
    try jsonmod.escapeInto(arena, buf, s);
    try buf.append(arena, '"');
}

fn printErr(arena: std.mem.Allocator, code: u8, err_type: []const u8, message: []const u8) void {
    const me = jsonmod.escapeAlloc(arena, message) catch {
        term.err("{\"err\":{\"code\":110,\"type\":\"internal_error\"}}\n");
        return;
    };
    const j = std.fmt.allocPrint(arena, "{{\"err\":{{\"code\":{d},\"type\":\"{s}\",\"message\":\"{s}\"}}}}\n", .{ code, err_type, me }) catch return;
    term.err(j);
}

/// `tau init` — write (or, with to_stdout, print) a commented starter
/// ~/.config/tau/config.json seeded from detected provider env keys.
/// Returns a semantic exit code.
pub fn run(
    io: std.Io,
    arena: std.mem.Allocator,
    env: *std.process.Environ.Map,
    force: bool,
    to_stdout: bool,
    provider_opt: ?[]const u8,
) !u8 {
    const det = try detectKeys(arena, env);
    const p = pickProvider(det, provider_opt);
    const body = try renderConfig(arena, det, p);

    if (to_stdout) {
        term.out(body);
        return 0;
    }

    const path = configfile.path(arena, env) orelse {
        printErr(arena, 110, "internal_error", "HOME is not set -- cannot locate ~/.config/tau/config.json");
        return 110;
    };

    const exists = blk: {
        _ = std.Io.Dir.cwd().readFileAlloc(io, path, arena, .unlimited) catch |err| {
            if (err == error.FileNotFound) break :blk false;
            break :blk true; // exists but unreadable -- still refuse to clobber
        };
        break :blk true;
    };
    if (exists and !force) {
        const msg = std.fmt.allocPrint(arena, "config already exists: {s} -- pass --force to overwrite", .{path}) catch "config already exists";
        printErr(arena, 1, "already_exists", msg);
        return 1;
    }

    // Parent dir: <HOME>/.config/tau (path ends in "/config.json").
    if (std.mem.lastIndexOfScalar(u8, path, '/')) |idx| {
        std.Io.Dir.cwd().createDirPath(io, path[0..idx]) catch {};
    }
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = path, .data = body });

    var out: std.ArrayList(u8) = .empty;
    try out.appendSlice(arena, "{\"config_path\":");
    try appendJsonStr(arena, &out, path);
    try out.appendSlice(arena, ",\"provider\":");
    try appendJsonStr(arena, &out, p.name);
    try out.appendSlice(arena, ",\"created\":true,\"overwritten\":");
    try out.appendSlice(arena, if (exists) "true" else "false");
    try out.appendSlice(arena, ",\"detected_env_keys\":[");
    for (det.keys, 0..) |k, i| {
        if (i != 0) try out.append(arena, ',');
        try appendJsonStr(arena, &out, k.env_key);
    }
    if (det.tau_fallback) {
        if (det.keys.len > 0) try out.append(arena, ',');
        try appendJsonStr(arena, &out, "TAU_API_KEY");
    }
    try out.appendSlice(arena, "]}\n");
    term.out(out.items);
    return 0;
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------
const testing = std.testing;

test "detectKeys finds provider env keys in table order" {
    var ar = std.heap.ArenaAllocator.init(testing.allocator);
    defer ar.deinit();
    const a = ar.allocator();

    var env = std.process.Environ.Map.init(a);
    try env.put("OPENAI_API_KEY", "sk-oai");
    try env.put("XIAOMI_API_KEY", "xm-key");

    const det = try detectKeys(a, &env);
    try testing.expectEqual(@as(usize, 2), det.keys.len);
    // Provider-table order: xiaomi is listed before openai.
    try testing.expectEqualStrings("xiaomi", det.keys[0].provider);
    try testing.expectEqualStrings("XIAOMI_API_KEY", det.keys[0].env_key);
    try testing.expectEqualStrings("openai", det.keys[1].provider);
    try testing.expect(!det.tau_fallback);
}

test "detectKeys reports TAU_API_KEY as the fallback" {
    var ar = std.heap.ArenaAllocator.init(testing.allocator);
    defer ar.deinit();
    const a = ar.allocator();

    var env = std.process.Environ.Map.init(a);
    try env.put("TAU_API_KEY", "tau-key");
    // Empty values don't count as detected.
    try env.put("DEEPSEEK_API_KEY", "");

    const det = try detectKeys(a, &env);
    try testing.expectEqual(@as(usize, 0), det.keys.len);
    try testing.expect(det.tau_fallback);
}

test "pickProvider: explicit > detected > default" {
    var ar = std.heap.ArenaAllocator.init(testing.allocator);
    defer ar.deinit();
    const a = ar.allocator();

    var env = std.process.Environ.Map.init(a);
    try env.put("OPENAI_API_KEY", "sk-oai");
    const det = try detectKeys(a, &env);

    // Explicit --provider beats detection.
    try testing.expectEqualStrings("deepseek", pickProvider(det, "deepseek").name);
    // Detection picks the first provider with a set env key.
    try testing.expectEqualStrings("openai", pickProvider(det, null).name);

    var empty_env = std.process.Environ.Map.init(a);
    const none = try detectKeys(a, &empty_env);
    // Nothing detected, no flag: the in-code default provider.
    try testing.expectEqualStrings(cfgmod.providers[0].name, pickProvider(none, null).name);
    // An unknown explicit name falls back to detection/default.
    try testing.expectEqualStrings("openai", pickProvider(det, "bogus").name);
}

test "renderConfig emits a commented JSONC config that never leaks key values" {
    var ar = std.heap.ArenaAllocator.init(testing.allocator);
    defer ar.deinit();
    const a = ar.allocator();

    var env = std.process.Environ.Map.init(a);
    try env.put("OPENAI_API_KEY", "sk-secret-value");
    const det = try detectKeys(a, &env);
    const p = pickProvider(det, null);

    const body = try renderConfig(a, det, p);
    // Comments present, detected env var referenced by name, chosen provider set.
    try testing.expect(std.mem.indexOf(u8, body, "//") != null);
    try testing.expect(std.mem.indexOf(u8, body, "OPENAI_API_KEY") != null);
    try testing.expect(std.mem.indexOf(u8, body, "\"provider\": \"openai\"") != null);
    // The secret value itself must never be written.
    try testing.expect(std.mem.indexOf(u8, body, "sk-secret-value") == null);

    // Stripped of comments, the body is valid JSON selecting that provider.
    const stripped = try configfile.stripComments(a, body);
    const parsed = try std.json.parseFromSliceLeaky(
        struct { provider: []const u8 },
        a,
        stripped,
        .{ .ignore_unknown_fields = true },
    );
    try testing.expectEqualStrings("openai", parsed.provider);
}

test "renderConfig with no detected keys notes that none were found" {
    var ar = std.heap.ArenaAllocator.init(testing.allocator);
    defer ar.deinit();
    const a = ar.allocator();

    var env = std.process.Environ.Map.init(a);
    const det = try detectKeys(a, &env);
    const body = try renderConfig(a, det, cfgmod.providers[0]);
    try testing.expect(std.mem.indexOf(u8, body, "none detected") != null);
    try testing.expect(std.mem.indexOf(u8, body, "* set") == null);
}
